spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
      client:
        registration:
          ms-services:
            provider: spring
            client-id: ms-services
            client-secret: rootroot
            authorization-grant-type: client_credentials
            scope:
              - read
              - write
            client-name: ms-services
        provider:
          spring:
            token-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SPRING_TOKEN_URI}
