spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_ISSUER_URI}
      client:
        registration:
          client-app:
            provider: spring
            client-id: client-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            #redirect-uri: "http://127.0.0.1:8080/authorized"
            redirect-uri: ${SPRING_SECURITY_OAUTH2_REDIRECT_FRONT_URI}
            scope:
              - openid
              - profile
              - read
              - write
            client-name: client-app
        provider:
          spring:
            authorization-uri: ${SPRING_SECURITY_AUTHORIZATION_URI}
            token-uri: "http://authserver-app:9000/oauth2/token"
            user-info-uri: "http://authserver-app:9000/userinfo"
            jwk-set-uri: "http://authserver-app:9000/.well-known/jwks.json"